## Лабораторная работа №1 | Вариант 4

Выполнила: Бурганова Элина

### 1. Numpy

In [ ]:
import numpy as np

1. Найти индексы не нулевых элементов массива [1,2,0,0,4,0]

In [89]:
arr = [1, 2, 0, 0, 4, 0]
idx = np.nonzero(arr)
idx

(array([0, 1, 4]),)

2. Создайте единичную матрицу размером 3х3

In [90]:
matrix = np.ones([3, 3])
matrix

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

3. Создайте матрицу-шахматную доску 8х8 используя функцию `tile`

In [91]:
checker_matrix = np.array([[0, 1], [1, 0]])
checker_matrix = np.tile(checker_matrix, (4, 4))
checker_matrix

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

4. Дан 1D массив, удалите все элементы которые входят в диапазон `[3, 8]` inplace

In [92]:
arr = np.array([0, 4, 4, 2, 1, 4, 8, 7, 10, 15])
arr = np.delete(arr, [3, 4, 5, 6, 7, 8])
arr

array([ 0,  4,  4, 15])

5. Создайте случайный вектор размером 10 элементов и замените максимальный элемент на 0

In [93]:
arr = np.random.randint(10000, size=10)
arr[np.where(arr == np.max(arr))] = 0
arr

array([3589, 9143, 4286, 8834,    0, 6589, 5225, 2951, 5815, 1029])

6. Как распечатать все значения в массиве?

In [94]:
import sys
arr = np.arange(103)
np.set_printoptions(threshold=sys.maxsize)
arr

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
        78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
        91,  92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102])

7. Рассмотрим случайный вектор с формой 100х2, представляющей координаты, и найдем расстояния от точки к точке

In [95]:
coordinates = np.random.random((100, 2))
x = np.atleast_2d(coordinates[:,  0])
y = np.atleast_2d(coordinates[:, 1])

result = np.sqrt((x - x.T)**2 + (y - y.T)**2)
result

array([[0.        , 0.4142406 , 0.50255256, 0.07732752, 0.25522288,
        0.26557188, 0.38603764, 0.50418877, 0.25128517, 0.29315149,
        0.43236772, 0.38637604, 0.52174075, 0.34899219, 0.28738017,
        0.68088498, 0.30163943, 0.43879193, 0.28272191, 0.27005426,
        0.2090798 , 0.21881391, 0.14966233, 0.62116402, 0.15162368,
        0.60254808, 0.25968681, 0.33077757, 0.32732067, 0.4629551 ,
        0.21182832, 0.58338258, 0.37703646, 0.59754699, 0.1485676 ,
        0.62876783, 0.50090793, 0.49976283, 0.29126454, 0.56981752,
        0.42583367, 0.75933064, 0.42748072, 0.29829363, 0.20460185,
        0.36910811, 0.29461613, 0.57217143, 0.42425289, 0.35767822,
        0.44309078, 0.58388452, 0.46935749, 0.43986568, 0.64586874,
        0.16157581, 0.5049326 , 0.44296619, 0.26516695, 0.59287844,
        0.13467102, 0.40224136, 0.32739221, 0.16699747, 0.39735571,
        0.39456671, 0.56332023, 0.41207819, 0.39366292, 0.75162991,
        0.5258349 , 0.43708646, 0.41408214, 0.29

8. Как конвертировать массив float(32 bit) к массиву целых чисел (integer 32 bit) in place?

In [96]:
# используя метод view

float32_arr = (np.random.rand(10)*100).astype(np.float32)
int32_arr = float32_arr.view(np.int32)
int32_arr[:] = float32_arr
int32_arr

array([49, 89, 96,  5, 21, 98, 17, 99, 53, 52], dtype=int32)

9. Как прочитать заданный файл?
```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

In [88]:
data = '''1, 2, 3, 4, 5
6, , , 7, 8
, , 9, 10, 11'''

data_rows = [row.split(",") for row in data.splitlines()]

result = np.array(
    [
        [float(el.strip()) if el.strip() else np.nan for el in row]
         for row in data_rows
    ]
)

result

array([[ 1.,  2.,  3.,  4.,  5.],
       [ 6., nan, nan,  7.,  8.],
       [nan, nan,  9., 10., 11.]])

10. Какой эквивалент enumerate для numpy массивов?

In [ ]:
arr = np.array([[4, 2, 7], [3, 5, 1], [6, 8, 9]])
for index, value in np.ndenumerate(arr):
    print(index, value)

(0, 0) 4
(0, 1) 2
(0, 2) 7
(1, 0) 3
(1, 1) 5
(1, 2) 1
(2, 0) 6
(2, 1) 8
(2, 2) 9


### 2. Pandas

Найдите ответы на вопросы или выполните действия с предложенным датасетом

Файл: `russian-housing-market.csv`

```
price_doc - Цена продажи
id - Id транзакции
timestamp - Дата транзакции
full_sq - суммарная площадь в квадратных метрах, включая лоджию, валконы и отдельные нежилые помещения
life_sq - жилая площаль в квадратных метрах, исключая лоджии, балконы и прочие нежилые помещения
floor - для апартаментов, этаж помещения
max_floor - количество этажей в здании
material - материал стен
build_year - год постройки
num_room - количество жилых комнат
kitch_sq - площадь кухни
state - состояние апартаментов
product_type - покупка или инвестиция собственника-арендатора
sub_area - название района
```

In [ ]:
import pandas as pd

In [80]:
DATA_PATH = "/content/russian-housing-market.csv"
df = pd.read_csv(DATA_PATH)
df.head(5)

id   timestamp  full_sq  life_sq  floor  max_floor  material  build_year  \
0   1  2011-08-20       43     27.0    4.0        NaN       NaN         NaN   
1   2  2011-08-23       34     19.0    3.0        NaN       NaN         NaN   
2   3  2011-08-27       43     29.0    2.0        NaN       NaN         NaN   
3   4  2011-09-01       89     50.0    9.0        NaN       NaN         NaN   
4   5  2011-09-05       77     77.0    4.0        NaN       NaN         NaN   

   num_room  kitch_sq  state product_type           sub_area  price_doc  
0       NaN       NaN    NaN   Investment           Bibirevo    5850000  
1       NaN       NaN    NaN   Investment  Nagatinskij Zaton    6000000  
2       NaN       NaN    NaN   Investment     Tekstil'shhiki    5700000  
3       NaN       NaN    NaN   Investment             Mitino   13100000  
4       NaN       NaN    NaN   Investment          Basmannoe   16331452

1. Посчитайте количество записей в датасете с отсутствующей информацией о жилой площади жилого помещения

In [81]:
#True is NaN, False is not NaN
missing_data = df["life_sq"].isna().sum()
missing_data

6383

2. Предложите способ заменить отсутствующие значения из пункта 1 и реализуйте его. Способ нужно аргументировать(сказать почему это достаточно хорошее приближение)

In [82]:
# Заполним пропущенную информацию средним значением жилой площади для соответствующего диапазона полной площади, так как эти значения сильно коррелируют
df['life_sq'] = df.groupby(pd.cut(df['full_sq'], bins=10))['life_sq'].transform(lambda x: x.fillna(x.mean()))


missing_data_after = df['life_sq'].isna().sum()

missing_data_after

<ipython-input-82-71b2ce232027>:2: FutureWarning:

The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.



0

3. Какие значения имеет 25, 50 и 75 перцентили полной площади помещения

In [ ]:
df["full_sq"].quantile(0.25), df["full_sq"].quantile(0.5), df["full_sq"].quantile(0.75)

(38.0, 49.0, 63.0)

4. Посчитайте среднюю стоимость продажи помещений с общей площадью от 50 до 70 квадратных метров

In [97]:
mean_price = df[(df["full_sq"] >= 50) & (df["full_sq"] <= 70)]["price_doc"].mean()
mean_price

7243041.190994609

5. Какая максимальная этажность здания представлена в датасете

In [98]:
max_floor = df["max_floor"].max()
max_floor

117.0

6. Выявите район с самым дорогим жильем

In [99]:
area = df.groupby(["sub_area"])["price_doc"].mean().idxmax()
area

'Hamovniki'

7. Посчитайте среднюю стоимость за квадратный метр жилья в Митино(Mitino)

In [100]:
mean_price_per_square = df[df["sub_area"] == "Mitino"].apply(lambda x: (x["price_doc"] / x["full_sq"]), axis=1).mean()
mean_price_per_square

171841.39999559196

8. Посчитайте среднюю площадь комнаты в Бибирево

In [102]:
mean_square = df[df["sub_area"] == "Bibirevo"].apply(lambda x: (x["life_sq"] / x["num_room"]), axis=1).mean()
mean_square

16.09058813116169

9. Проанализируйте есть ли разница в цене между квартирами на 1 и 9 этажах

In [103]:
diff = df[df["floor"] == 9]["price_doc"].mean() - df[df["floor"] == 1]["price_doc"].mean()
diff

1198202.9969607173

10. Найдите минимальную стоимость квартиры с жилой площадью не менее 60 квадратных метров, не менее чем 3мя комнатами и не ниже чем на 5 этаже

In [104]:
min_price = df[(df["life_sq"] >= 60) & (df["num_room"] >= 3) & (df["floor"] >= 5)]["price_doc"].min()
min_price

1000000

### 3. Визуализация

Используя библиотеки matplotlib/sns/plotly/pandas и набор данных представленный ранее визуализируйте

In [6]:
import plotly.express as px

1. Как менялась средняя цена квартиры в Нагатинском Затоне(Nagatinski Zaton) с течением времени

In [86]:
df["timestamp"] = pd.to_datetime(df["timestamp"],format= '%Y-%m-%d')

data = df[df["sub_area"] == "Nagatinskij Zaton"].groupby(df["timestamp"].dt.to_period('M'))["price_doc"].median()

fig = px.line(x=data.index.to_timestamp(), y=data, title='Mean price change in Nagatinski Zaton')
fig.update_layout(yaxis_title='mean price',
                   xaxis_title='time',
                  title={
                      'font': dict(size=25),
                      'x': 0.5,
                      'y': 0.9
                  })
fig.show()

2. Постройте гистограмму распределения цен на квартиры с общей площадью более 50 кв.метров

In [105]:
fig_2 = px.histogram(df[df["full_sq"] >= 50], "price_doc",
                   title="Distribution of apartament price with square>=50",
                   nbins=200)
fig_2.update_layout(title={
                      'font': dict(size=25),
                      'x': 0.5,
                      'y': 0.95
                  })
fig_2.show()

3. Визуализируйте количество проданных квартир в разных районах

In [110]:
fig_3 = px.histogram(df, "sub_area",
                   title="Amount of sold apartments",
                   nbins=50)
fig_3.update_layout(title={
                      'font': dict(size=25),
                      'x': 0.5,
                      'y': 0.95
                  })
fig_3.show()

4. Постройте box plot отображающий распределение полных площадей квартир в Басманном районе

In [109]:
fig_4 = px.box(df[df["sub_area"] == "Basmannoe"], y="full_sq",
              title="Distribution of the apartment's full square in Basmannoe",
              template='presentation'
              )
fig_4.update_traces(quartilemethod="exclusive")
fig_4.update_layout(title={
                      'font': dict(size=25),
                      'x': 0.5,
                      'y': 0.95
                  })
fig_4.show()


5. Визуализируйте зависимость средней стоимости квартир в зависимости от этажа

In [108]:
data = df.groupby(["floor"])["price_doc"].mean()

fig_5 = px.line(x=data.index.tolist(),
                  y=data,
                  title="Apartament mean price dependence on floor",
                  markers=True)
fig_5.update_layout(yaxis_title='mean price',
                   xaxis_title='floor',
                   title={
                      'font': dict(size=25),
                      'x': 0.5,
                      'y': 0.95
                  })
fig_5.show()

6. Покажите как меняется средняя площадь квартир в зависимости от района

In [107]:
data = df.groupby(["sub_area"])["full_sq"].mean()

fig_6 = px.scatter(x=data.index.tolist(),
                  y=data,
                  title="Apartament mean price dependence on area")
fig_6.update_layout(yaxis_title='full square',
                   xaxis_title='area',
                   title={
                      'font': dict(size=25),
                      'x': 0.5,
                      'y': 0.95
                  })
fig_6.show()

7. Постройте график изменения медианной цены на квартиру менее 50 кв. метров за период с 2011 до 2014 года*

\* Задание на доп. балл

In [106]:
filtered_df = df[(df["timestamp"] >= pd.Timestamp(2011, 1, 1)) & (df["timestamp"] <= pd.Timestamp(2013, 12, 31)) & (df["full_sq"] < 50)]

data = filtered_df.groupby(df["timestamp"].dt.to_period('M'))["price_doc"].median()

fig_7 = px.line(x=data.index.to_timestamp(),
                  y=data,
                  title="Apartament median price",
                  markers=True)
fig_7.update_layout(yaxis_title='median price',
                   xaxis_title='year',
                   title={
                      'font': dict(size=25),
                      'x': 0.5,
                      'y': 0.95
                  })
fig_7.show()